[tool.poetry]
name = "homework-14-1"
version = "0.1.0"
description = ""
authors = ["Andrey <pise4kan8@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
